### ISSUE TITLE
Page Not Found at root

### ISSUE THREAD

**Issue by EvgeniyBlinov** [andrey900/SlimCMS#12]
Page Not Found
at / (root) page
add 2 pages 
with empty url_prefix
with / url_prefix

**Comment by andrey900** [comment]
Thx - fixed. 
Later in the plans must be validated these fields...

**Comment by EvgeniyBlinov** [comment]
How can I test it?
https://dpaste.de/QDOH
http://pix.toile-libre.org/upload/original/1466355759.png
https://dpaste.de/g73y
https://dpaste.de/OR5r

**Comment by andrey900** [comment]
Вы используете драйвер mysql, на текущий момент нет нормального функционала миграций. Файлы дампов не совсем корректные - скажем прямо... Нужно создать страницу без привязки к разделу, в поле "code" ничего не указывать - это и будет главная страница. Если мне не изменяет память, на данный момент url_prefix - мертв.
Дамп для главной страницы записи - https://dpaste.de/wtng . Должно завестись
