### ISSUE TITLE
after install admin/sections Slim Application Error

### ISSUE THREAD

**Issue by 1f7** [andrey900/SlimCMS#15]
admin panel -> sections -> show all categories
also pages
also users
also groups

Slim Application Error

The application could not run because of the following error:
Details
Type: Error
Message: Call to a member function make() on null
File: /var/www/run5/vendor/illuminate/pagination/LengthAwarePaginator.php
Line: 140

**Comment by andrey900** [comment]
Yes, maybe this error after new release illuminate/pagination. I fixed next release.

**Comment by andrey900** [comment]
fixed
