### ISSUE TITLE
Installation issues in xampp

### ISSUE THREAD

**Issue by samitrimal** [andrey900/SlimCMS#18]
Installation page has issues with design while trying  on localhost. The design is not loading as in the screenshot attached below. However I was able to install it. None of the links work when installed in the sub folder. 
![sliminstall](https://cloud.githubusercontent.com/assets/706536/19014818/0d5652b8-8817-11e6-98b9-31486b92b614.PNG)

**Comment by andrey900** [comment]
don't use subfolder. Correct path in browser http://localhost/ . You web server It must be settings redirect all queries for public/index.php, Static files(*.jpeg, *.js, *.css ...) redirect for root folder /public/
