### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by geckozilla** [andrey900/SlimCMS#19]
I get this error after installing slim cms

`
Fatal error: Uncaught RuntimeException: A facade root has not been set. in D:\xampp7\htdocs\vendor\illuminate\support\Facades\Facade.php:234 Stack trace: #0 D:\xampp7\htdocs\modules\Core\Source\MicroModules\LoggerModule.php(65): Illuminate\Support\Facades\Facade::__callStatic('connection', Array) #1 D:\xampp7\htdocs\vendor\pimple\pimple\src\Pimple\Container.php(113): Modules\Core\Source\MicroModules\LoggerModule->Modules\Core\Source\MicroModules\{closure}(Object(Slim\Container)) #2 D:\xampp7\htdocs\vendor\slim\slim\Slim\Container.php(123): Pimple\Container->offsetGet('logger') #3 D:\xampp7\htdocs\modules\Core\Source\MicroModules\LoggerModule.php(24): Slim\Container->get('logger') #4 D:\xampp7\htdocs\src\Modules\ModuleLoader.php(145): Modules\Core\Source\MicroModules\LoggerModule->initialization() #5 D:\xampp7\htdocs\src\Modules\ModuleLoader.php(90): SlimCMS\Modules\ModuleLoader::initProcess(Object(Modules\Core\Source\MicroModules\LoggerModule)) #6 D:\xampp7\htdocs\modules\Core\Module.php(237): SlimCMS\Modules\ModuleLoader in D:\xampp7\htdocs\vendor\illuminate\support\Facades\Facade.php on line 234
`

**Comment by andrey900** [comment]
Thanks, i resolve in next version, maybe this error occurred after an upgrade Illuminate package...

**Comment by andrey900** [comment]
please change line "6" at file "./modules/Core/Source/MicroModules/LoggerModule.php"
use Illuminate\Support\Facades\DB;

to
use Illuminate\Database\Capsule\Manager as DB;
