### ISSUE TITLE
error after install.use mysql 

### ISSUE THREAD

**Issue by lazycms** [andrey900/SlimCMS#20]
( ! ) Fatal error: Uncaught exception 'ReflectionException' with message 'Class Core does not exist' in /home/vagrant/Code/slimrbac/vendor/illuminate/container/Container.php on line 734
( ! ) ReflectionException: Class Core does not exist in /home/vagrant/Code/slimrbac/vendor/illuminate/container/Container.php on line 734

**Comment by andrey900** [comment]
clear directory: rm -rf /cache/*
show in file "/modules/Core/config.json" - params:installed must be value set "true";(after installed)
please add insert line dump debuger in /app/bootstrap/app.php in line 68
dd($container->modules->getModules()); - in container must module name "Core"

**Comment by whsecurity** [comment]
Hello,
I tried the above solution with this output:
Container {#22 ▼
  #resolved: []
  #bindings: []
  #methodBindings: []
  #instances: []
  #aliases: []
  #abstractAliases: []
  #extenders: []
  #tags: []
  #buildStack: []
  #with: []
  +contextual: []
  #reboundCallbacks: []
  #globalResolvingCallbacks: []
  #globalAfterResolvingCallbacks: []
  #resolvingCallbacks: []
  #afterResolvingCallbacks: []
}

Keep up the good work!
