### ISSUE TITLE
can't get URL to show

### ISSUE THREAD

**Issue by codingarrow** [andrey900/SlimCMS#23]
using xampp I followed instruction and installed (readme)
```

http://127.0.0.1/SlimCMS

Page Not Found

The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.
Visit the Home Page
```

I even followed the solutions here https://github.com/slimphp/Slim/issues/2294

Thank you

**Comment by andrey900** [comment]
try without using xampp, or reconfigure the virtual host to the public folder
