### ISSUE TITLE
Where is route file ? 

### ISSUE THREAD

**Issue by arirah** [andrey900/SlimCMS#24]
Where is route files ? If i need more routes from where i can set it ?

**Comment by andrey900** [comment]
you must create your own module, in method registerRoute(), register the necessary paths, install the module later.
class must be:
   const MODULE_NAME = 'ModuleName';
and
   protected static $loaded = false;

The module should be located in the modules/ModuleName folder.
Required files: Module.php -> extends App\Source\BaseModule,
info.json: https://github.com/andrey900/SlimCMS/blob/master/modules/Sections/info.json
config.json: https://github.com/andrey900/SlimCMS/blob/master/modules/Sections/config.json

You can use the module generator, it will create the necessary structure, and files, you will have to fill the registerRoute method only to install it. You can do this by enabled the options in the system: developersMode
