### ISSUE TITLE
404 

### ISSUE THREAD

**Issue by Nooxm** [andrey900/SlimCMS#26]
Приветствую!

Установил, но не работает...

Перехожу по урлу http://site/SlimCMS/auth/login

Пишет:

Page Not Found
The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.

Visit the Home Page

**Comment by andrey900** [comment]
К сожалению работает только из корня. (нет поддержки подкаталога)
Например: http://localhost:8080/auth/login

**Comment by Nooxm** [comment]
Из корня тоже не работает. Файлы сайта в корне должны быть или в папке slimCMS ? По умолчанию с гита устанавливается в эту папку))) Пробовал скачать в slimcms, извлек файлы в корень, установил coposer в корне. Не работает((

**Comment by andrey900** [comment]
Публичная часть сайта находится в папке public. Все что в ней должно быть доступно
остальные папки должны быть на уровень выше

То есть если у тебя вебсервер смотрит в каталог D:/wamp/www/ тебе нужно разместить все в D:/wamp/, а папку public переименовать в www

**Comment by Nooxm** [comment]
Понятно, спасибо)))
